//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Components = new HashSet<Component>();
            this.Hydrologies = new HashSet<Hydrology>();
            this.HydrologyStageDischarges = new HashSet<HydrologyStageDischarge>();
            this.HydrologySedimentAccumulations = new HashSet<HydrologySedimentAccumulation>();
            this.LIDs = new HashSet<LID>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MunicipalId { get; set; }
        public string Comments { get; set; }
        public string LocationDescription { get; set; }
        public string NearestIntersection { get; set; }
        public string Address { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<decimal> Easting { get; set; }
        public Nullable<decimal> Northing { get; set; }
        public Nullable<int> Magnification { get; set; }
        public string AdjacentLandUse { get; set; }
        public Nullable<int> DefaultPictureId { get; set; }
        public string Municipality { get; set; }
        public string DesignConsultant { get; set; }
    
        public virtual LandUse LandUse { get; set; }
        public virtual ComponentPicture ComponentPicture { get; set; }
        public virtual AssetFacility AssetFacility { get; set; }
        public virtual AssetSite AssetSite { get; set; }
        public virtual AssetStructure AssetStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hydrology> Hydrologies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HydrologyStageDischarge> HydrologyStageDischarges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HydrologySedimentAccumulation> HydrologySedimentAccumulations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LID> LIDs { get; set; }
    }
}
