//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetStructure
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Ownership { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> DrainageArea { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Manning { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Slope { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public Nullable<bool> HasBaseflow { get; set; }
        public Nullable<decimal> Baseflow { get; set; }
        public Nullable<decimal> OverflowElevation { get; set; }
        public Nullable<decimal> UpstreamInvertElevation { get; set; }
        public Nullable<decimal> DownstreamInvertElevation { get; set; }
        public Nullable<decimal> UpstreamChannelDepth { get; set; }
        public Nullable<decimal> DownstreamChannelDepth { get; set; }
        public Nullable<decimal> UpstreamChannelWidth { get; set; }
        public Nullable<decimal> DownstreamChannelWidth { get; set; }
        public Nullable<decimal> LossCoefficient { get; set; }
        public Nullable<decimal> UpstreamX { get; set; }
        public Nullable<decimal> UpstreamY { get; set; }
        public Nullable<decimal> DownstreamX { get; set; }
        public Nullable<decimal> DownstreamY { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual StructureMaterial StructureMaterial { get; set; }
        public virtual StructureOwnership StructureOwnership { get; set; }
        public virtual StructureType StructureType { get; set; }
    }
}
