//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AssetFacility
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Function { get; set; }
        public string Description { get; set; }
        public Nullable<int> YearAssumed { get; set; }
        public string CofANumber { get; set; }
        public Nullable<int> CofADate { get; set; }
        public string SubdivisionNumber { get; set; }
        public string SubdivisionName { get; set; }
        public string BlockNumber { get; set; }
        public Nullable<decimal> BlockArea { get; set; }
        public Nullable<int> TotalVolume { get; set; }
        public bool PondOnline { get; set; }
        public string Watershed { get; set; }
        public Nullable<int> PoolMinimumVolume { get; set; }
        public Nullable<decimal> PoolDesignedMaxDepth { get; set; }
        public Nullable<int> PoolDesignedVolume { get; set; }
        public Nullable<decimal> PoolAsBuiltMaxDepth { get; set; }
        public Nullable<int> PoolAsBuiltVolume { get; set; }
        public string AcessDescription { get; set; }
        public bool DrivewayPresent { get; set; }
        public string DrivewayMaterial { get; set; }
        public bool TurnAroundPresent { get; set; }
        public bool GatePresent { get; set; }
        public bool LockPresent { get; set; }
        public Nullable<decimal> ContributingDrainageAreaMajor { get; set; }
        public Nullable<decimal> ContributingDrainageAreaMinor { get; set; }
        public Nullable<decimal> QuantityFloodControlDepth { get; set; }
        public Nullable<decimal> QuantityFloodControlVolume { get; set; }
        public Nullable<decimal> QualityControlDepth { get; set; }
        public Nullable<decimal> QualityControlVolume { get; set; }
        public Nullable<decimal> ExtendedDetentionErosionControlDepth { get; set; }
        public Nullable<decimal> ExtendedDetentionErosionControlVolume { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string Custom7 { get; set; }
        public string Custom8 { get; set; }
        public string Custom9 { get; set; }
        public string Custom10 { get; set; }

        public virtual Asset Asset { get; set; }
        public virtual FacilityFunction FacilityFunction { get; set; }
        public virtual FacilityStatu FacilityStatu { get; set; }
        public virtual FacilityType FacilityType { get; set; }
    }
}
