//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.AssignInspectionTaskToMobiles = new HashSet<AssignInspectionTaskToMobile>();
            this.ComponentPictures = new HashSet<ComponentPicture>();
            this.Component1 = new HashSet<Component>();
            this.Inspections = new HashSet<Inspection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int ParentAssetId { get; set; }
        public Nullable<int> ParentComponentId { get; set; }
        public string Description { get; set; }
        public string LocationDescription { get; set; }
        public decimal Easting { get; set; }
        public decimal Northing { get; set; }
        public Nullable<int> Magnification { get; set; }
        public string Action { get; set; }
        public string Attributes { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string Staff { get; set; }
        public string Equipment { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string Custom7 { get; set; }
        public string Custom8 { get; set; }
        public string Custom9 { get; set; }
        public string Custom10 { get; set; }
        public string Comments { get; set; }
        public Nullable<int> DefaultPictureId { get; set; }
    
        public virtual Asset Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignInspectionTaskToMobile> AssignInspectionTaskToMobiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentPicture> ComponentPictures { get; set; }
        public virtual ComponentPicture ComponentPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Component1 { get; set; }
        public virtual Component Component2 { get; set; }
        public virtual ComponentType ComponentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
    }
}
