//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Hydrology
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public int Year { get; set; }
        public decimal Area { get; set; }
        public decimal Length { get; set; }
        public decimal Imperviousness { get; set; }
        public decimal Slope { get; set; }
        public decimal Construction { get; set; }
        public int MOELevel { get; set; }
        public string Comments { get; set; }

        public virtual Asset Asset { get; set; }
    }
}
