//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LID()
        {
            this.LIDComponents = new HashSet<LIDComponent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentAssetId { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<int> DesignType { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> YearAssumed { get; set; }
        public string Ownership { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual BMPType BMPType { get; set; }
        public virtual LIDDesignType LIDDesignType { get; set; }
        public virtual StructureOwnership StructureOwnership { get; set; }
        public virtual LIDStatu LIDStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDComponent> LIDComponents { get; set; }
    }
}
