//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDComponentTemplate
    {
        public int Id { get; set; }
        public string BMPType { get; set; }
        public Nullable<int> Component { get; set; }
    
        public virtual BMPType BMPType1 { get; set; }
        public virtual LIDComponentType LIDComponentType { get; set; }
    }
}
