//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIDComponent()
        {
            this.AssignInspectionTaskToMobiles = new HashSet<AssignInspectionTaskToMobile>();
            this.LIDComponentPictures = new HashSet<LIDComponentPicture>();
            this.LIDDesignComponentInspectionIndicators = new HashSet<LIDDesignComponentInspectionIndicator>();
            this.LIDPastInspections = new HashSet<LIDPastInspection>();
        }
    
        public int Id { get; set; }
        public int LIDNameID { get; set; }
        public Nullable<int> Component { get; set; }
        public string Description { get; set; }
        public string Equipment { get; set; }
        public string BMPTypeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignInspectionTaskToMobile> AssignInspectionTaskToMobiles { get; set; }
        public virtual BMPType BMPType { get; set; }
        public virtual LID LID { get; set; }
        public virtual LIDComponentType LIDComponentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDComponentPicture> LIDComponentPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDDesignComponentInspectionIndicator> LIDDesignComponentInspectionIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDPastInspection> LIDPastInspections { get; set; }
    }
}
