//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDComponentIndicatorTemplate
    {
        public int Id { get; set; }
        public int Description { get; set; }
        public int Action { get; set; }
        public string BMPTypeCode { get; set; }
        public string InspectionType { get; set; }
    
        public virtual BMPType BMPType { get; set; }
        public virtual LIDInspectionIndicator LIDInspectionIndicator { get; set; }
        public virtual LIDComponentType LIDComponentType { get; set; }
        public virtual LIDInspectionType LIDInspectionType { get; set; }
    }
}
