//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDDesignComponentInspectionIndicator
    {
        public int Id { get; set; }
        public int LIDComponentId { get; set; }
        public string Frequency { get; set; }
        public int Indicator { get; set; }
    
        public virtual LIDComponent LIDComponent { get; set; }
        public virtual LIDInspectionType LIDInspectionType { get; set; }
        public virtual LIDInspectionIndicator LIDInspectionIndicator { get; set; }
    }
}
