//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDInspectionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIDInspectionType()
        {
            this.AssignInspectionTaskToMobiles = new HashSet<AssignInspectionTaskToMobile>();
            this.LIDComponentIndicatorTemplates = new HashSet<LIDComponentIndicatorTemplate>();
            this.LIDDesignComponentInspectionIndicators = new HashSet<LIDDesignComponentInspectionIndicator>();
            this.LIDPastInspections = new HashSet<LIDPastInspection>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignInspectionTaskToMobile> AssignInspectionTaskToMobiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDComponentIndicatorTemplate> LIDComponentIndicatorTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDDesignComponentInspectionIndicator> LIDDesignComponentInspectionIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDPastInspection> LIDPastInspections { get; set; }
    }
}
