//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIDPastInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIDPastInspection()
        {
            this.LIDComponentPictures = new HashSet<LIDComponentPicture>();
            this.Maintenances = new HashSet<Maintenance>();
        }
    
        public int Id { get; set; }
        public int LIDComponentID { get; set; }
        public Nullable<int> Indictor { get; set; }
        public string Condition { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string InspectedBy { get; set; }
        public string Comments { get; set; }
        public string Frequency { get; set; }
    
        public virtual ConditionType ConditionType { get; set; }
        public virtual LIDComponent LIDComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIDComponentPicture> LIDComponentPictures { get; set; }
        public virtual LIDInspectionIndicator LIDInspectionIndicator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual LIDInspectionType LIDInspectionType { get; set; }
    }
}
