//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceStandardTaskResource
    {
        public int Id { get; set; }
        public int MaintenanceStandardTaskId { get; set; }
        public int ResourceID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual MaintenanceStandardTask MaintenanceStandardTask { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
