//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserLogon { get; set; }
        public string UserName { get; set; }
        public string UserInitials { get; set; }
        public bool IsAdministrator { get; set; }
        public bool IsReadOnly { get; set; }
        public bool Deleted { get; set; }
    }
}
